plugins:
  # - prettier-plugin-nunjucks # I'd like this, but it has whitespace bugs
  - prettier-plugin-jinja-template

overrides:
  - files: ["*.njk", "*.html"]
    options:
      # parser: nunjucks
      parser: jinja-template

htmlWhitespaceSensitivity: css
